//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSBase2
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     此代码由工具生成。
    //     运行时版本:4.0.30319.42000
    //
    //     对此文件的更改可能会导致不正确的行为，并且如果
    //     重新生成代码，这些更改将会丢失。
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Runtime.Serialization;



    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Contact", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int idField;

        private string nameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TemplageData", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class TemplageData : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Module[] modulesField;

        private Template[] templatesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Module[] modules
        {
            get
            {
                return this.modulesField;
            }
            set
            {
                this.modulesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Template[] templates
        {
            get
            {
                return this.templatesField;
            }
            set
            {
                this.templatesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Module", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class Module : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string JSFrameworkField;

        private string descriptionField;

        private int edit_flagField;

        private string files_textField;

        private int idField;

        private string languageField;

        private string module_nameField;

        private int template_idField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JSFramework
        {
            get
            {
                return this.JSFrameworkField;
            }
            set
            {
                this.JSFrameworkField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int edit_flag
        {
            get
            {
                return this.edit_flagField;
            }
            set
            {
                this.edit_flagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string files_text
        {
            get
            {
                return this.files_textField;
            }
            set
            {
                this.files_textField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string module_name
        {
            get
            {
                return this.module_nameField;
            }
            set
            {
                this.module_nameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int template_id
        {
            get
            {
                return this.template_idField;
            }
            set
            {
                this.template_idField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Template", Namespace = "http://schemas.datacontract.org/2004/07/")]
    public partial class Template : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string JSFrameworkField;

        private string areasField;

        private string descriptionField;

        private int edit_flagField;

        private string filesField;

        private string htmlField;

        private int idField;

        private string languageField;

        private string template_nameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JSFramework
        {
            get
            {
                return this.JSFrameworkField;
            }
            set
            {
                this.JSFrameworkField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string areas
        {
            get
            {
                return this.areasField;
            }
            set
            {
                this.areasField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int edit_flag
        {
            get
            {
                return this.edit_flagField;
            }
            set
            {
                this.edit_flagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string files
        {
            get
            {
                return this.filesField;
            }
            set
            {
                this.filesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string html
        {
            get
            {
                return this.htmlField;
            }
            set
            {
                this.htmlField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string template_name
        {
            get
            {
                return this.template_nameField;
            }
            set
            {
                this.template_nameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ICodeService")]
    public interface ICodeService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICodeService/DoWork", ReplyAction = "http://tempuri.org/ICodeService/DoWorkResponse")]
        string DoWork(string p, Contact Contact1);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICodeService/DoWork", ReplyAction = "http://tempuri.org/ICodeService/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync(string p, Contact Contact1);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICodeService/CreateCode", ReplyAction = "http://tempuri.org/ICodeService/CreateCodeResponse")]
        JSBase.Result[] CreateCode(string token, JSBase.CSParameter Param);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICodeService/CreateCode", ReplyAction = "http://tempuri.org/ICodeService/CreateCodeResponse")]
        System.Threading.Tasks.Task<JSBase.Result[]> CreateCodeAsync(string token, JSBase.CSParameter Param);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICodeService/Synchronize", ReplyAction = "http://tempuri.org/ICodeService/SynchronizeResponse")]
        TemplageData Synchronize(string token, string language, string framework);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICodeService/Synchronize", ReplyAction = "http://tempuri.org/ICodeService/SynchronizeResponse")]
        System.Threading.Tasks.Task<TemplageData> SynchronizeAsync(string token, string language, string framework);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICodeService/CreateCode2", ReplyAction = "http://tempuri.org/ICodeService/CreateCode2Response")]
        JSBase.Result[] CreateCode2(JSBase.Page p, JSBase.PageDetail pd);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICodeService/CreateCode2", ReplyAction = "http://tempuri.org/ICodeService/CreateCode2Response")]
        System.Threading.Tasks.Task<JSBase.Result[]> CreateCode2Async(JSBase.Page p, JSBase.PageDetail pd);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodeServiceChannel : ICodeService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodeServiceClient : System.ServiceModel.ClientBase<ICodeService>, ICodeService
    {

        public CodeServiceClient()
        {
        }

        public CodeServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public CodeServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CodeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CodeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public string DoWork(string p, Contact Contact1)
        {
            return base.Channel.DoWork(p, Contact1);
        }

        public System.Threading.Tasks.Task<string> DoWorkAsync(string p, Contact Contact1)
        {
            return base.Channel.DoWorkAsync(p, Contact1);
        }

        public JSBase.Result[] CreateCode(string token, JSBase.CSParameter Param)
        {
            return base.Channel.CreateCode(token, Param);
        }

        public System.Threading.Tasks.Task<JSBase.Result[]> CreateCodeAsync(string token, JSBase.CSParameter Param)
        {
            return base.Channel.CreateCodeAsync(token, Param);
        }

        public TemplageData Synchronize(string token, string language, string framework)
        {
            return base.Channel.Synchronize(token, language, framework);
        }

        public System.Threading.Tasks.Task<TemplageData> SynchronizeAsync(string token, string language, string framework)
        {
            return base.Channel.SynchronizeAsync(token, language, framework);
        }

        public JSBase.Result[] CreateCode2(JSBase.Page p, JSBase.PageDetail pd)
        {
            return base.Channel.CreateCode2(p, pd);
        }

        public System.Threading.Tasks.Task<JSBase.Result[]> CreateCode2Async(JSBase.Page p, JSBase.PageDetail pd)
        {
            return base.Channel.CreateCode2Async(p, pd);
        }
    } 

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name = "CSParameter", Namespace = "http://schemas.datacontract.org/2004/07/JSBase")]
        public partial class CSParameter : object, System.Runtime.Serialization.IExtensibleDataObject
        {

            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

            private JSBase.Page pageField;

            private JSBase.PageDetail[] page_detailField;

            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public JSBase.Page page
            {
                get
                {
                    return this.pageField;
                }
                set
                {
                    this.pageField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public JSBase.PageDetail[] page_detail
            {
                get
                {
                    return this.page_detailField;
                }
                set
                {
                    this.page_detailField = value;
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name = "Page", Namespace = "http://schemas.datacontract.org/2004/07/JSBase")]
        public partial class Page : object, System.Runtime.Serialization.IExtensibleDataObject
        {

            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

            private string AuthorField;

            private string controllerField;

            private string controller_areaField;

            private string descriptionField;

            private int idField;

            private string page_nameField;

            private string page_name_textField;

            private string parent_menu_codeField;

            private int template_idField;

            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Author
            {
                get
                {
                    return this.AuthorField;
                }
                set
                {
                    this.AuthorField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string controller
            {
                get
                {
                    return this.controllerField;
                }
                set
                {
                    this.controllerField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string controller_area
            {
                get
                {
                    return this.controller_areaField;
                }
                set
                {
                    this.controller_areaField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string description
            {
                get
                {
                    return this.descriptionField;
                }
                set
                {
                    this.descriptionField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public int id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string page_name
            {
                get
                {
                    return this.page_nameField;
                }
                set
                {
                    this.page_nameField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string page_name_text
            {
                get
                {
                    return this.page_name_textField;
                }
                set
                {
                    this.page_name_textField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string parent_menu_code
            {
                get
                {
                    return this.parent_menu_codeField;
                }
                set
                {
                    this.parent_menu_codeField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public int template_id
            {
                get
                {
                    return this.template_idField;
                }
                set
                {
                    this.template_idField = value;
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name = "PageDetail", Namespace = "http://schemas.datacontract.org/2004/07/JSBase")]
        public partial class PageDetail : object, System.Runtime.Serialization.IExtensibleDataObject
        {

            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

            private string areaField;

            private string class_nameField;

            private JSBase.ColumnSet[] columnsField;

            private string commentsField;

            private int idField;

            private int module_idField;

            private string name_textField;

            private string table_descriptionField;

            private string table_nameField;

            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string area
            {
                get
                {
                    return this.areaField;
                }
                set
                {
                    this.areaField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string class_name
            {
                get
                {
                    return this.class_nameField;
                }
                set
                {
                    this.class_nameField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public JSBase.ColumnSet[] columns
            {
                get
                {
                    return this.columnsField;
                }
                set
                {
                    this.columnsField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string comments
            {
                get
                {
                    return this.commentsField;
                }
                set
                {
                    this.commentsField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public int id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public int module_id
            {
                get
                {
                    return this.module_idField;
                }
                set
                {
                    this.module_idField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string name_text
            {
                get
                {
                    return this.name_textField;
                }
                set
                {
                    this.name_textField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string table_description
            {
                get
                {
                    return this.table_descriptionField;
                }
                set
                {
                    this.table_descriptionField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string table_name
            {
                get
                {
                    return this.table_nameField;
                }
                set
                {
                    this.table_nameField = value;
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name = "ColumnSet", Namespace = "http://schemas.datacontract.org/2004/07/JSBase")]
        public partial class ColumnSet : object, System.Runtime.Serialization.IExtensibleDataObject
        {

            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

            private string ColumnCaptionField;

            private string ColumnDescriptionField;

            private string ColumnNameField;

            private int FlagIdentityField;

            private int FlagPrimaryField;

            private bool IsIdentityField;

            private int LengthField;

            private string PrimaryFieldField;

            private int SizeField;

            private string TypeField;

            private string dataField;

            private string htmlTypeField;

            private bool isInsertField;

            private bool isRequiredField;

            private bool isShowField;

            private bool isUpdateField;

            private bool isWhereField;

            private string staticValueField;

            private string validField;

            private int widthField;

            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ColumnCaption
            {
                get
                {
                    return this.ColumnCaptionField;
                }
                set
                {
                    this.ColumnCaptionField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ColumnDescription
            {
                get
                {
                    return this.ColumnDescriptionField;
                }
                set
                {
                    this.ColumnDescriptionField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ColumnName
            {
                get
                {
                    return this.ColumnNameField;
                }
                set
                {
                    this.ColumnNameField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public int FlagIdentity
            {
                get
                {
                    return this.FlagIdentityField;
                }
                set
                {
                    this.FlagIdentityField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public int FlagPrimary
            {
                get
                {
                    return this.FlagPrimaryField;
                }
                set
                {
                    this.FlagPrimaryField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool IsIdentity
            {
                get
                {
                    return this.IsIdentityField;
                }
                set
                {
                    this.IsIdentityField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public int Length
            {
                get
                {
                    return this.LengthField;
                }
                set
                {
                    this.LengthField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PrimaryField
            {
                get
                {
                    return this.PrimaryFieldField;
                }
                set
                {
                    this.PrimaryFieldField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public int Size
            {
                get
                {
                    return this.SizeField;
                }
                set
                {
                    this.SizeField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Type
            {
                get
                {
                    return this.TypeField;
                }
                set
                {
                    this.TypeField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string data
            {
                get
                {
                    return this.dataField;
                }
                set
                {
                    this.dataField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string htmlType
            {
                get
                {
                    return this.htmlTypeField;
                }
                set
                {
                    this.htmlTypeField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool isInsert
            {
                get
                {
                    return this.isInsertField;
                }
                set
                {
                    this.isInsertField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool isRequired
            {
                get
                {
                    return this.isRequiredField;
                }
                set
                {
                    this.isRequiredField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool isShow
            {
                get
                {
                    return this.isShowField;
                }
                set
                {
                    this.isShowField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool isUpdate
            {
                get
                {
                    return this.isUpdateField;
                }
                set
                {
                    this.isUpdateField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool isWhere
            {
                get
                {
                    return this.isWhereField;
                }
                set
                {
                    this.isWhereField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string staticValue
            {
                get
                {
                    return this.staticValueField;
                }
                set
                {
                    this.staticValueField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string valid
            {
                get
                {
                    return this.validField;
                }
                set
                {
                    this.validField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public int width
            {
                get
                {
                    return this.widthField;
                }
                set
                {
                    this.widthField = value;
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name = "Result", Namespace = "http://schemas.datacontract.org/2004/07/JSBase")]
        public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject
        {

            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

            private string ContextField;

            private string FileNameField;

            private string FileTypeField;

            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Context
            {
                get
                {
                    return this.ContextField;
                }
                set
                {
                    this.ContextField = value;
                }
            }

            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FileName
            {
                get
                {
                    return this.FileNameField;
                }
                set
                {
                    this.FileNameField = value;
                }
            } 
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FileType
            {
                get
                {
                    return this.FileTypeField;
                }
                set
                {
                    this.FileTypeField = value;
                }
            }
        }
    }

 
